### ISSUE TITLE
Porting code to Python 3

### ISSUE THREAD

**Issue by deebuls** [ma-sultan/short-answer-grader#2]
I tried porting the code to python 3.
[2to3](https://docs.python.org/2/library/2to3.html) was helpful in automating the whole process.

Also I had to do the same with the standford-corenlp-python library.

But the code fails in the socket connections: 

'''
Traceback (most recent call last):
  File "pretrainedGrader.py", line 66, in <module>
    score = grade(question, ref_answer, student_response)
  File "pretrainedGrader.py", line 39, in grade
    feature_vector = extract_features(question, ref_answer, student_response)
  File "pretrainedGrader.py", line 12, in extract_features
    sts_alignment(ref_answer, student_response)
  File "/home/deebuls/Documents/digi-klausur/short-answer-grader/featureExtraction.py", line 50, in sts_alignment
    sentence1_parse_result = parseText(sentence1)
  File "/home/deebuls/Documents/digi-klausur/short-answer-grader/coreNlpUtil.py", line 20, in parseText
    parseResult = nlp.parse(sentences)
  File "/home/deebuls/Documents/digi-klausur/short-answer-grader/coreNlpUtil.py", line 14, in parse
    return json.loads(self.server.parse(text))
  File "/home/deebuls/Documents/digi-klausur/short-answer-grader/jsonrpc.py", line 934, in __call__
    return self.__req(self.__name, args, kwargs)
  File "/home/deebuls/Documents/digi-klausur/short-answer-grader/jsonrpc.py", line 907, in __req
    resp = self.__data_serializer.loads_response( resp_str )
  File "/home/deebuls/Documents/digi-klausur/short-answer-grader/jsonrpc.py", line 598, in loads_response
    raise RPCInvalidRPC("""Invalid Response, "jsonrpc" must be a string.""")
jsonrpc.RPCInvalidRPC: <RPCFault -32600: 'Invalid Request.' ('Invalid Response, "jsonrpc" must be a string.')>

'''

What i understand is Python has introduced new format called Byte.
So string in python2 is different from python3.

I have commited the converted python 3 files in my branch here : https://github.com/deebuls/short-answer-grader/tree/python3_port

Also the python 3 port of stanford-corenlp-python is here : https://github.com/deebuls/stanford-corenlp-python/tree/port_python3

I am currently looking into the problem. Maybe you can provide some insights.

**Comment by avivajpeyi** [comment]
Tried to do the same and am having some issues. Did you manage to get it to work in python 3?

**Comment by deebuls** [comment]
Yes, I got it working.
Its here: https://github.com/deebuls/short-answer-grader/tree/python3_port

We also went ahead and have made a object oriented code around it : 
Please check the new code here : https://github.com/rameshjesswani/Semantic-Textual-Similarity
